### ISSUE TITLE
Move metamodels to own file, away from regression.py?

### ISSUE THREAD

**Issue by blengerich** [cnellington/Contextualized#61]

**Comment by cnellington** [comment]
The metamodels are model-specific so I think it makes sense to leave them in regression. Similarly the NOTMAD metamodel would go in networks. The correlation metamodel makes explicit use of the regression metamodels, so I also think it makes sense to import from regression there. 

On this topic, it might be good to move regularization losses into regression since I think they're also built specifically for the regression metamodels.

**Comment by blengerich** [comment]
Metamodels, datasets, and models seem to be fairly distinct types of regression objects. What would you think about making a regression directory, and splitting the types into their own files in the same regression directory?

**Comment by cnellington** [comment]
That makes sense, especially because each model has attributes like "loss" and "dataloader" which require model-specific implementations but are universal to all model types.

**Comment by blengerich** [comment]
Refactored in #60
